networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys
      - AUTH_SERVICE_URL=http://auth-service:8081
      - CORE_SERVICE_URL=http://core-service:8082
      - PAYMENT_SERVICE_URL=http://payment-service:8083
    depends_on:
      - postgres
      - core-service
    networks:
      - backend

  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: core-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys
      - DB_CORE_HOST=postgres
      - DB_CORE_PORT=5432
      - DB_CORE_NAME=core_db
      - DB_CORE_USERNAME=core_user
      - DB_CORE_PASSWORD=core_strong_pass_456
    depends_on:
      - postgres
    networks:
      - backend

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USERNAME=auth_user
      - DB_PASSWORD=auth_strong_pass_123
      - BOT_TOKEN=8625864637:AAEtNeyvcK-umEwmkADj1rlZtOgoid2nVB8
    depends_on:
      - postgres
    networks:
      - backend




volumes:
  postgres_data: