version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2024.11

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 24.0.9
      - run:
          name: Test Docker
          command: |
            docker --version
            echo "Docker is available"

workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: dev