version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2024.11

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Test build
          command: |
            echo "Hello from CircleCI"
            ls -la

workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: dev