server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

  cloud:
    gateway:
      x-forwarded:
        enabled: true
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: core-service-route
          uri: ${CORE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/core/**, /api/v2/core/**, /api/v3/core/**
          filters:
            - StripPrefix=0

        - id: payment-service-route
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - StripPrefix=0

        - id: auth-service-docs
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/docs/auth/**
          filters:
            - 'RewritePath=/docs/auth/(?<segment>.*), /$\{segment}'

        - id: core-service-docs
          uri: ${CORE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/docs/core/**
          filters:
            - 'RewritePath=/docs/core/(?<segment>.*), /$\{segment}'

        - id: payment-service-docs
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/docs/payment/**
          filters:
            - 'RewritePath=/docs/payment/(?<segment>.*), /$\{segment}'

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://localhost:3000
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true



springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /docs/auth/v3/api-docs
      - name: Core Service
        url: /docs/core/v3/api-docs
      - name: Payment Service
        url: /docs/payment/v3/api-docs
      - name: Admin Service
        url: /docs/admin/v3/api-docs
    urls-primary-name: Core Service

jwt:
  secret: aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys
