server:
  port: 8082

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5433/core_db
    username: core_user
    password: core_strong_pass_456
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys