spring:
  application:
    name: auth-service
  profiles:
    active: db,sms,auth

server:
  port: 8081
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:aZUyHFCj6SUG2hI5sGHFifB2iQkfIY3nTztuTVdws4Ys}
  time: 3600000
  refresh-time: 2592000000
